version: "3"

services:
  envoy:
    build:
      context: ./docker/envoy
    image: twpt-server/envoy
    ports:
      - "10123:8081"
    depends_on:
      - server
    networks:
      - backend
    restart: unless-stopped
  server:
    build:
      context: .
      dockerfile: ./cmd/server/Dockerfile
    image: twpt-server/golang-server
    entrypoint: ["/sbin/tini", "--", "/server", "--db=root:@tcp(db)/twpt", "--port=10000"]
    ports:
      - "10124:10000"
    depends_on:
      - db
    networks:
      - backend
    restart: unless-stopped
  db:
    image: mariadb@sha256:9da6213d1a5714c4585c9c0003c51510b320d6f60e53d78701fe1e194126249f
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MARIADB_DATABASE: twpt
    networks:
      - backend
    restart: unless-stopped

networks:
  backend:
